# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
import random
tensor = torch.rand(size=(7, 7))
tensor, tensor.shape

(tensor([[0.5374, 0.9198, 0.3049, 0.8836, 0.2491, 0.9373, 0.3947],
         [0.0183, 0.3537, 0.0751, 0.7910, 0.6673, 0.4577, 0.7864],
         [0.5137, 0.4261, 0.5158, 0.5273, 0.5461, 0.4786, 0.3354],
         [0.4159, 0.7997, 0.4222, 0.2734, 0.2871, 0.7178, 0.7410],
         [0.0946, 0.8890, 0.2767, 0.4638, 0.1085, 0.6943, 0.1600],
         [0.0382, 0.5586, 0.2463, 0.6754, 0.3746, 0.4571, 0.4278],
         [0.4340, 0.3381, 0.1596, 0.5807, 0.3574, 0.0522, 0.4845]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
another_random_tensor = torch.rand(size = (1, 7))
# Perform matrix multiplication
result = torch.matmul(tensor, another_random_tensor.T)
result, result.shape


(tensor([[2.5782],
         [2.1188],
         [2.0312],
         [2.3031],
         [1.6728],
         [1.8081],
         [1.6172]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED)
first_random_tensor = torch.rand(size=(7,7))

second_random_tensor = torch.rand(size=(1,7))

# Matrix multiply tensors
result = first_random_tensor @ second_random_tensor.T    # result = torch.matmul(first_random_tensor, second_random_tensor.T)

result, result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [2]:
import torch
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
first_random_tensor = torch.rand(size = (2, 3))
second_random_tensor = torch.rand(size=(2, 3))

print(f"Device: {device}\n{first_random_tensor} \n{second_random_tensor}")

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) 
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
#device = "cuda" if torch.cuda.is_available() else "cpu"
first_random_tensor = first_random_tensor.to(device)
second_random_tensor = second_random_tensor.to(device)
result = torch.matmul(first_random_tensor, second_random_tensor.T)
result, result.device, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 device(type='cuda', index=0),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
max = result.max()
# Find min
min = result.min()

max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
indexMax = torch.argmax(result)
# Find arg min
indexMin = torch.argmin(result)

indexMin, indexMax

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
new_tensor = tensor.squeeze()

# Print out tensors and their shapes
tensor, tensor.shape, new_tensor, new_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))